### ISSUE TITLE
Missing Classes: JacksonJsonReader and JacksonJsonWriter

### ISSUE THREAD

**Issue by esfand** [sijuv/protobuf-codec#1]
I can not find these classes in the Jackson's jar file or any other places.
Could you please tell where they can be found.

Thanks for sharing.
Esfand

**Comment by sijuv** [comment]
my bad, forgot to commit those 2 after some refactoring, updated.
Let me know how it goes, also added support for extension fields

**Comment by esfand** [comment]
It works perfectly now!

Thanks for such a quick response.
